apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.14.0

    helm:
      values: |
        expose:
          type: ingress
          tls:
            enabled: false

          ingress:
            className: nginx
            hosts:
              core: harbor.local

            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"

        externalURL: http://harbor.local:32318

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true